name: "spark-application-workflow-non-prod"
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
    branches:
      - master
jobs:
    build:
        name: "Build"
        runs-on: ubuntu-latest
        steps:
        - name: "Checkout code"
          uses: actions/checkout@v3
        - name: "trigger build"
          run: "echo 'Building Spark Application...'"
        - name: "Post build action"
          run: "echo 'executing post build actions'"