name: "spark-application-workflow-non-prod"
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
env:
  WORKFLOW_NAME: "spark-application-workflow-non-prod"
  JAVA_VERSION: '11'
jobs:
    build:
        env:
          JOB_NAME: "build"
        name: "Build"
        runs-on: ubuntu-latest
        steps:
        - name: "Checkout code"
          uses: actions/checkout@v4
        - name: "Java sdk seutp"
          uses: actions/setup-java@v4
          with:
            java-version: '11'
            distribution: 'temurin'
            chace: 'maven'
        - name: "trigger build for $WORKFLOW_NAME $JOB_NAME"
          run: mvn -B clean package -DskipTests --file pom.xml
        - name: "Upload build artifacts"
          uses: actions/upload-artifact@v4
          with:
            name: "spark-application-artifact"
            path: target/*.jar
    test:
        env:
          JOB_NAME: "test"
        name: "Test"
        runs-on: ubuntu-latest
        needs: build
        steps:
        - name: "Checkout code"
          run : "echo 'Checking out code...'"
        - name: "operating system inspection"
          run: "echo 'Operating system is ${{ runner.os }}'"
        - name: "trigger test"
          run: "echo 'Testing $WORKFLOW_NAME - $JOB_NAME Spark Application...'"
        - name: "Post test action"
          run: "echo '${{ toJson(github) }}'"
    deploy:
        name: "Deploy"
        runs-on: ubuntu-latest
        needs: test
        steps:
        - name: "Checkout code"
          run : "echo 'Checking out code...'"
        - name: "trigger deploy"
          run: "echo 'Deploying $WORKFLOW_NAME - ${{github.job.deploy.name}} ... '"
        - name: "Post deploy action"
          run: "echo 'executing post deploy actions'"